-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.5
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
    -   id: forbid-new-submodules
    -   id: check-added-large-files
    -   id: check-merge-conflict
