- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0  # Use the ref you want to point at
  hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.7.3
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
